---
title: "I4TB PLHIV 3HP cost effectiveness analysis"
author: "Julia Shin"
output: pdf_document
---

# Step 0: Parameters

```{r step2a parameters}    
time=11 #(2020~2030)
imp.time=10 #3HP effectiveness time =10years

a <- c( 'I4TB.g1', 'I4TB.g2', 'other.g1', 'other.g2')

TBrr <- 0.016    #TB reactivation rate/ Golub, AIDS 2007; Sterling AIDS 2016
eff <- 0.9       #Efficacy of 3HP/ Sterling, N Engl J Med 2011
comp <- 0.8      #Completion of 3HP/ Sterling, N Engl J Med 2011
r <- 0.03        #Discount Rate
fatal<- 0.11     #TB case-fatality for HIV+ on TB treatment
UwHIV <- 0.947   #Utility of people with HIV on ART
LE <- 27         #Life expectancy of HIV-positive individual on ART
UwTB <- 0.601    #Utility of TB with HIV+ 
LTBI <-0.23
  
price1 = 15 #2020-2021
price2 = 12 #2022-2023
price3 = 10  #2024~ (Scenario1)
price4 = 1  #2024~ (Scenario2)

df <- 114.85/98.1 #Inflation: 2008 -> 2018 USD (GDP deflator)
df2009 <- 114.85/98.848 #Inflation: 2009 -> 2018 USD (GDP deflator)
tox1 <- 0.082
tox2 <- 0.003
liver.cost <- 39.41 #2009USD, SA Naidoo(2015)
cbc.cost <- 6.47
ele.cost <- 19.33
lab.cost <- liver.cost + cbc.cost + ele.cost #SA, 2009usd

#2008
cOPD.brz <- 2.4
cOPD.cmb <- 1.64
cOPD.eth <- 0.77
cOPD.ghn <- 1.59
cOPD.ind <- 2.2
cOPD.idn <- 4.37
cOPD.kny <- 1.73                         
cOPD.mlw <- 0.67
cOPD.mzb <- 1.06
cOPD.sa <- 9.54
cOPD.tnz <- 1.11
cOPD.zbw <- 2.62

cOPD1 <- c(cOPD.eth, cOPD.ghn, cOPD.kny, cOPD.mlw, cOPD.mzb, cOPD.sa, cOPD.tnz, cOPD.zbw)

cOPD.g1 <- mean(cOPD1)

cOPD2 <- c(cOPD.brz, cOPD.cmb, cOPD.idn, cOPD.ind)

cOPD.g2 <- mean(cOPD2)

cOPD <- c(cOPD.g1, cOPD.g2,cOPD.g1, cOPD.g2 )

#2009
clab.brz <- lab.cost*cOPD.brz/cOPD.sa
clab.cmb <- lab.cost*cOPD.cmb/cOPD.sa
clab.eth <- lab.cost*cOPD.eth/cOPD.sa
clab.ghn <- lab.cost*cOPD.ghn/cOPD.sa
clab.ind <- lab.cost*cOPD.ind/cOPD.sa
clab.idn <- lab.cost*cOPD.idn/cOPD.sa
clab.kny <- lab.cost*cOPD.kny/cOPD.sa
clab.mlw <- lab.cost*cOPD.mlw/cOPD.sa
clab.mzb <- lab.cost*cOPD.mzb/cOPD.sa
clab.sa <- lab.cost*cOPD.sa/cOPD.sa
clab.tnz <- lab.cost*cOPD.tnz/cOPD.sa
clab.zbw <- lab.cost*cOPD.zbw/cOPD.sa

clab1 <- c(clab.eth, clab.ghn, clab.kny, clab.mlw, clab.mzb, clab.sa, clab.tnz, clab.zbw)

clab.g1 <- mean(clab1)

clab2 <- c(clab.brz, clab.cmb, clab.idn, clab.ind)
clab.g2 <- mean(clab2)

clab <- c(clab.g1, clab.g2, clab.g1, clab.g2)
                
#2008
cinp.brz <- 17.23 #secondary-level hospital cost per bed day us$ 2008
cinp.cmb <- 5.91
cinp.eth <- 2.07
cinp.ghn <- 5.09
cinp.ind <- 8.83
cinp.idn <- 19.42
cinp.kny <- 5.65
cinp.mlw <- 1.73
cinp.mzb <- 2.82
cinp.sa <-  57.65
cinp.tnz <- 3.39
cinp.zbw <- 22.53 * 98.1/90.959 #USD 2005 -> 2008

cinp1 <- c(cinp.eth, cinp.ghn, cinp.kny, cinp.mlw, cinp.mzb, cinp.sa, cinp.tnz, cinp.zbw)

cinp.g1 <- mean(cinp1)

cinp2 <- c(cinp.brz, cinp.cmb, cinp.idn, cinp.ind)

cinp.g2 <- mean(cinp2)

cinp <- c(cinp.g1, cinp.g2, cinp.g1, cinp.g2)

cGDP.brz <- 8920.8
cGDP.cmb <- 1512.1
cGDP.eth <- 772.3
cGDP.ghn <- 2202.3
cGDP.ind <- 2015.6 	
cGDP.idn <- 3893.6
cGDP.kny <- 1710.5 
cGDP.mlw <- 389.4
cGDP.mzb <- 490.2 
cGDP.sa  <- 6374.0
cGDP.tnz <- 1050.7
cGDP.zbw <- 2147.0  
  			  			  			 			 		 						 						  	

cGDP1 <- c(cGDP.eth, cGDP.ghn, cGDP.kny, cGDP.mlw, cGDP.mzb, cGDP.sa, cGDP.tnz, cGDP.zbw)

cGDP.g1 <- mean(cGDP1)

cGDP2 <- c(cGDP.brz, cGDP.cmb, cGDP.ind, cGDP.idn)
cGDP.g2 <- mean(cGDP2)

cGDP <- c(cGDP.g1, cGDP.g2, cGDP.g1, cGDP.g2)

cTB <- exp(-2.2+1.1*log(cGDP))


cART = 64


#mild toxicity requires one lab + one visit
tox1cost <- clab*df2009 + cOPD*df 

names(tox1cost) <- c( "tox1cost.g1", "tox2cost.g2","tox1cost.g1", "tox2cost.g2")

#severe toxicity requires one lab + 7days hospitalization (*Holland et al.)
tox2cost <- clab*df2009 + cinp*df*7

names(tox2cost) <- c( "tox2cost.g1", "tox2cost.g2", "tox2cost.g1", "tox2cost.g2")

```

# Step 1: Setting Up The population (PLHIV on ART)

``` {r step1a PLHIV on ART} 

# est. number of HIV diagnosed in 2020 
## (2 years delay from estimated infection)
n.brz <- 53000
n.cmb <- 880
n.eth <- 23000
n.ghn <- 20000
n.ind <- 84595
n.idn <- 46000
n.kny <- 46000
n.mlw <- 38000
n.mzb <- 150000
n.sa <-  240000
n.tnz <- 72000
n.zbw <- 38000
n.I4TB.g1 <- 627000 #African countries
n.I4TB.g2 <- 184475 #Asia, Latin
n.other.g1 <- 473000
n.other.g2 <- 459525

pop <- c(n.brz, n.cmb, n.eth, n.ghn, n.ind, n.idn, n.kny, n.mlw, n.mzb, n.sa, n.tnz, n.zbw, n.I4TB.g1, n.I4TB.g2, n.other.g1, n.other.g2)

m.pop <- matrix(pop, nrow=1, ncol=16)

# Annual growth rate of HIV infection
pHIV.brz <- (n.brz /43000)^(1/10)-1
pHIV.cmb <- (n.cmb /2700)^(1/10)-1
pHIV.eth <- (n.eth/31000)^(1/10)-1
pHIV.ghn <- (n.ghn /22000)^(1/10)-1
pHIV.ind <- (88000/116000)^(1/8)-1
pHIV.idn <- (n.idn/63000)^(1/10)-1
pHIV.kny <- (n.kny /72000)^(1/10)-1
pHIV.mlw <- (n.mlw/55000)^(1/10)-1
pHIV.mzb <- (n.mzb/150000)^(1/10)-1
pHIV.sa <- (n.sa/410000)^(1/10)-1
pHIV.tnz <- (n.tnz/88000)^(1/10)-1
pHIV.zbw <- (n.zbw /65000)^(1/10)-1
pHIV.I4TB.g1 <- (n.I4TB.g1/893000)^(1/10)-1
pHIV.I4TB.g2 <- (n.I4TB.g2/223900)^(1/8)-1
pHIV.other.g1 <- (n.other.g1/555000)^(1/10)-1
pHIV.other.g2 <- (n.other.g2/428100)^(1/8)-1

m.pHIV <- matrix(c(0:0), nrow=16, ncol=16)
m.pHIV[1,1] <- pHIV.brz+1
m.pHIV[2,2] <- pHIV.cmb+1 
m.pHIV[3,3] <- pHIV.eth+1
m.pHIV[4,4] <- pHIV.ghn+1
m.pHIV[5,5] <- pHIV.ind +1
m.pHIV[6,6] <- pHIV.idn +1
m.pHIV[7,7] <- pHIV.kny+1
m.pHIV[8,8] <- pHIV.mlw+1
m.pHIV[9,9] <- pHIV.mzb +1
m.pHIV[10,10] <- pHIV.sa +1
m.pHIV[11,11] <- pHIV.tnz+1
m.pHIV[12,12] <- pHIV.zbw+1
m.pHIV[13,13] <- pHIV.I4TB.g1+1
m.pHIV[14,14] <- pHIV.I4TB.g2+1
m.pHIV[15,15] <- pHIV.other.g1+1
m.pHIV[16,16] <- pHIV.other.g2+1
 
m.pop%*%(m.pHIV)

## 2020~2030 # of PLHIV diagnosed
m <- matrix( ,nrow=time, ncol=16)
m[1,] <- m.pop 
for (i in 2:time) {
    m[i, ] = m[i-1, ]%*%(m.pHIV)
  }  

# ART coverage
pART.brz <- 0.81
pART.cmb <- 0.855
pART.eth <- 0.81
pART.ghn <- 0.81
pART.ind <- 0.81
pART.idn <- 0.81
pART.kny <- 0.81
pART.mlw <- 0.81
pART.mzb <- 0.81
pART.sa <- 0.81
pART.tnz <- 0.828
pART.zbw <- 0.855
pART.g1 <- 0.81
pART.g2 <- 0.81

m.pART <- matrix(c(0:0), nrow=16, ncol=16)
m.pART[1,1] <- pART.brz
m.pART[2,2] <- pART.cmb 
m.pART[3,3] <- pART.eth
m.pART[4,4] <- pART.ghn
m.pART[5,5] <- pART.ind 
m.pART[6,6] <- pART.idn 
m.pART[7,7] <- pART.kny
m.pART[8,8] <- pART.mlw
m.pART[9,9] <- pART.mzb 
m.pART[10,10] <- pART.sa 
m.pART[11,11] <- pART.tnz
m.pART[12,12] <- pART.zbw
m.pART[13,13] <- pART.g1
m.pART[14,14] <- pART.g2
m.pART[15,15] <- pART.g1
m.pART[16,16] <- pART.g2
 
## 2020~2030 # of PLHIV on ART (newly enrolled)
m.ART <- matrix( ,nrow=time, ncol=16)
for (i in 1:time) {
m.ART[i, ] <- m [i, ]%*%m.pART 
    }  

#I4TB covers 5~60% of newly enrolled in ART care 
m.i4tb <- matrix(c(0:0) ,nrow=time, ncol=4)
m.i4tb[1,1] <- m.ART [1,13]%*%0.5 
m.i4tb[2,1] <- m.ART [2,13]%*%0.6 
m.i4tb[1,2] <- m.ART [1,14]%*%0.5 
m.i4tb[2,2] <- m.ART [2,14]%*%0.5 
 
rownames(m.i4tb) <- c(2020:2030)
colnames(m.i4tb) <- c('I4TB.g1', 'I4TB.g2', 'other.g1', 'other.g2')
```

# Step 2: Scenario1 of 3HP coverage

``` {r step2a catalytic impact population S1}  
m.new <- matrix(c(0:0), nrow=time, ncol=4)
m.new[1, 3] = m.ART[1,15]*0.25  #50%(half)*50%
m.new[2, 3] = m.ART[2,15]*0.3  #50%(half)*60%

for (i in 1:2) {
    m.new[i, 1] = m.ART[i,13 ]%*%0    #I4TB impact
    m.new[i, 2] = m.ART[i,14]*0    #I4TB impact
    m.new[i, 4] = m.ART[i,16]*0}    #no catalytic impact

for(i in 3:6) {
    m.new[i, 1] = m.ART[i,13]*(0.6+0.1*(i-3))
    m.new[i, 2] = m.ART[i,14]*(0.6+0.038*(i-3))
    m.new[i, 3] = m.ART[i,15]*(0.6+0.1*(i-3))*0.5+ m.ART[i,15]*(0.6+0.038*(i-3))*0.5
    m.new[i, 4] = m.ART[i,16]*(0.3+0.05*(i-3))}
    
for (i in 7:time) {
    m.new[i, 1] = m.ART[i,13 ]*(0.9+0.01*(i-6))
    m.new[i, 2] = m.ART[i,14]*(0.6+0.038*(i-3))
    m.new[i, 3] = m.ART[i,15]*(0.9+0.01*(i-6))*0.5+ m.ART[i,15]*(0.6+0.038*(i-3))*0.5
    m.new[i, 4] = m.ART[i,16]*(0.3+0.05*(i-3))
      } 

rownames(m.new) <- c(2020:2030)
colnames(m.new) <- c('I4TB.g1', 'I4TB.g2', 'other.g1', 'other.g2')

``` 

```{r step 2b catalytic impact on old PLWHIV S1}
# est. number of PLWHIV on ART in 2019 
## applied CAGR (2010-2018)
oldART.brz <- 654794
oldART.cmb <- 61718
oldART.eth <- 486752
oldART.ghn <- 126612
oldART.ind <- 1211000 #used 2017 data
oldART.idn <- 130185
oldART.kny <- 1180691
oldART.mlw <- 927677
oldART.mzb <- 1467110
oldART.sa <-  5492022
oldART.tnz <- 1312175
oldART.zbw <- 1308461
oldART.I4TB.g1 <- 12301499
oldART.I4TB.g2 <- 2057697
oldART.other.g1 <- 6366064
oldART.other.g2 <- 5740131

old.pop <- c(oldART.I4TB.g1, oldART.I4TB.g2, oldART.other.g1, oldART.other.g2)

m.oldpop <- matrix(old.pop , nrow=1, ncol=4)

m.old <- matrix(c(0:0) ,nrow=time, ncol=4)

for (i in 1:4) {
m.old[i,1] <- m.oldpop[1,1] * 0.05*i}

for (i in 5:6) {
m.old[i,1] <- m.oldpop[1,1] * 0.2}

for (i in 7:time) {
m.old[i,1] <- m.oldpop[1,1] * 0.01}

for (i in 2:5) {
m.old[i,2] <- m.oldpop[1,2] * 0.05}

for (i in 6:9) {
m.old[i,2] <- m.oldpop[1,2] * 0.1}

for (i in 10:time) {
m.old[i,2] <- m.oldpop[1,2] * 0.15}

m.old[1,3] <- m.oldpop[1,3] * 0.05*0.5  
m.old[2,3] <- m.oldpop[1,3] * 0.1*0.5 + m.oldpop[1,3] * 0.05*0.5
m.old[3,3] <- m.oldpop[1,3] * 0.15*0.5 + m.oldpop[1,3] * 0.05*0.5
m.old[4,3] <- m.oldpop[1,3] * 0.2*0.5 + m.oldpop[1,3] * 0.05*0.5
m.old[5,3] <- m.oldpop[1,3] * 0.2*0.5 + m.oldpop[1,3] * 0.05*0.5
m.old[6,3] <- m.oldpop[1,3] * 0.2*0.5 + m.oldpop[1,3] * 0.1*0.5

for (i in 7:9){
m.old[i,3] <- m.oldpop[1,3] * 0.01*0.5 + m.oldpop[1,3] * 0.1*0.5
}
for (i in 10:time){
m.old[i,3] <- m.oldpop[1,3] * 0.01*0.5 + m.oldpop[1,3] * 0.15*0.5
}
m.old[3,4] <- m.oldpop[1,4] * 0.02   
m.old[4,4] <- m.oldpop[1,4] * 0.03
m.old[5,4] <- m.oldpop[1,4] * 0.05
m.old[6,4] <- m.oldpop[1,4] * 0.05

for (i in 7:10){
m.old[i,4] <- m.oldpop[1,4] * 0.1
}
m.old[11,4] <- m.oldpop[1,4] * 0.15


rownames(m.old) <- c(2020:2030)
colnames(m.old) <- c('I4TB.g1', 'I4TB.g2', 'other.g1', 'other.g2')

m.S1 <- m.new + m.old 

m.total <- m.new + m.old + m.i4tb
```

# Step 3: I4TB direct effect  

``` {r step3a I4TB cohort survival projection}      

#1. I4TB cohort 

l.cohort.i4tb <- vector("list", 4)
for (k in 1:4) {
  l.cohort.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,2] 2021 cohorts
for (i in 1:2) {
  l.cohort.i4tb[[k]][1,i] <- t(m.i4tb)[k,i] 
    for (j in 2:imp.time) {
      l.cohort.i4tb[[k]][j,i] <- l.cohort.i4tb[[k]][j-1,i] - l.cohort.i4tb[[k]][j-1,i]*log(0.5)/-LE 
        }}
}

```

```{r Step3b I4TB case}
#2. case

l.case.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=group name
  l.case.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.case.i4tb[[k]][i,j] <- l.cohort.i4tb[[k]][i,j]*LTBI*(1-exp(-TBrr))*eff*comp 
}}
}
names(l.case.i4tb) <- paste0(a)

## discounted case averted

l.case.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.case.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,2] 2021 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.case.dis.i4tb[[k]][i,j] <- l.case.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.case.dis.i4tb) <- paste0(a)
```

```{r step3c I4TB death averted projection}

l.death.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.death.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.death.i4tb[[k]][i,j] <- l.case.i4tb[[k]][i,j]*fatal
}}
}
names(l.death.i4tb) <- paste0(a) 

## discounted death averted

l.death.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.death.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.death.dis.i4tb[[k]][i,j] <- l.death.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
} 

names(l.death.dis.i4tb) <- paste0(a)
```

```{r step3d I4TB DALY averted projection}

l.DALY.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.DALY.i4tb[[k]][i,j] <- l.death.i4tb[[k]][i,j]*UwHIV*((1/r)*(1-exp(-r*(LE-i+1)))) + l.case.i4tb[[k]][i,j]*(UwHIV-UwTB)
}}
}
names(l.DALY.i4tb) <- paste0(a) 

## discounted DALY averted

l.DALY.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.DALY.dis.i4tb[[k]][i,j] <- l.DALY.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
} 
names(l.DALY.dis.i4tb) <- paste0(a)

```

```{r step3e I4TB cost projection }
l.delivery.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.delivery.i4tb[[k]]<-matrix(NA, nrow=1, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2023 cohorts
  for (j in 1:2) {
  l.delivery.i4tb[[k]][1,j] <- l.cohort.i4tb[[k]][1,j]*(price1+3*cOPD[k]*df)*1.25
  }
}
names(l.delivery.i4tb) <- paste0(a)

#Toxicity

l.toxcost.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.toxcost.i4tb[[k]]<-matrix(NA, nrow=1, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
  for (j in 1:2) {
  l.toxcost.i4tb[[k]][1,j] <- l.cohort.i4tb[[k]][1,j]*tox1*tox1cost[k] +  l.cohort.i4tb[[k]][1,j]*tox2*tox2cost[k]
  }
}
names(l.toxcost.i4tb) <- paste0(a)
```

```{r step3f cost saved projection}

l.TBcostsaved.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.TBcostsaved.i4tb[[k]][i,j] <- l.case.i4tb[[k]][i,j]*cTB[k]
  }}
}
names(l.TBcostsaved.i4tb) <- paste0(a) 


l.ARTcost.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.ARTcost.i4tb[[k]][i,j] <- l.death.i4tb[[k]][i,j]*cART * (1/r)*(1-(1/((1+r)^(11-i))))*(1+r) 
  }}
}
names(l.ARTcost.i4tb) <- paste0(a)

## discounted cost saved

l.TBcostsaved.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.TBcostsaved.dis.i4tb[[k]][i,j] <- l.TBcostsaved.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.TBcostsaved.dis.i4tb) <- paste0(a)

l.ARTcost.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.ARTcost.dis.i4tb[[k]][i,j] <- l.ARTcost.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
} 
names(l.ARTcost.dis.i4tb) <- paste0(a)
```

``` {r step3g Cost effectiveness_I4TB}  
#1. case averted
case.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  case.sum.i4tb[k, ]<- colSums(l.case.dis.i4tb[[k]])  }

case.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
case.sum.dis.i4tb[, i] <- case.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Case.averted.i4tb<- rowSums(case.sum.dis.i4tb)

ct.Case.averted.i4tb <- as.matrix(Case.averted.i4tb)
sum.Case.averted.i4tb <- as.matrix(sum(Case.averted.i4tb))

f.Case.averted.i4tb <- rbind(ct.Case.averted.i4tb , sum.Case.averted.i4tb )
colnames(f.Case.averted.i4tb) <-c("cases averted")
rownames(f.Case.averted.i4tb) <-c(a,'total')

ft.Case.averted.i4tb <- as.data.frame(f.Case.averted.i4tb)

#2. death averted
death.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  death.sum.i4tb[k, ]<- colSums(l.death.dis.i4tb[[k]])  }

death.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
death.sum.dis.i4tb[, i] <- death.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Death.averted.i4tb<- rowSums(death.sum.dis.i4tb)

ct.Death.averted.i4tb <- as.matrix(Death.averted.i4tb)
sum.Death.averted.i4tb <- as.matrix(sum(Death.averted.i4tb))

f.Death.averted.i4tb <- rbind(ct.Death.averted.i4tb , sum.Death.averted.i4tb )
colnames(f.Death.averted.i4tb) <-c("Deaths averted")
rownames(f.Death.averted.i4tb) <-c(a,'total')

ft.Death.averted.i4tb <- as.data.frame(f.Death.averted.i4tb) 

#3. DALY averted
DALY.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  DALY.sum.i4tb[k, ]<- colSums(l.DALY.dis.i4tb[[k]])  }

DALY.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
DALY.sum.dis.i4tb[, i] <- DALY.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

DALY.averted.i4tb<- rowSums(DALY.sum.dis.i4tb)

ct.DALY.averted.i4tb <- as.matrix(DALY.averted.i4tb)
sum.DALY.averted.i4tb <- as.matrix(sum(DALY.averted.i4tb))

f.DALY.averted.i4tb <- rbind(ct.DALY.averted.i4tb , sum.DALY.averted.i4tb )
colnames(f.DALY.averted.i4tb) <-c("DALYs averted")

rownames(f.DALY.averted.i4tb) <-c(a,'total')

ft.DALY.averted.i4tb <- as.data.frame(f.DALY.averted.i4tb)


#4. Delivery cost
Delivery.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  Delivery.sum.i4tb[k, ]<- l.delivery.i4tb[[k]]  }

Delivery.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
Delivery.sum.dis.i4tb[, i] <- Delivery.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Delivery.cost.i4tb<- rowSums(Delivery.sum.dis.i4tb)

ct.Delivery.cost.i4tb <- as.matrix(Delivery.cost.i4tb)
sum.Delivery.cost.i4tb <- as.matrix(sum(Delivery.cost.i4tb))

f.Delivery.cost.i4tb <- rbind(ct.Delivery.cost.i4tb , sum.Delivery.cost.i4tb )
colnames(f.Delivery.cost.i4tb) <-c("Delivery cost")

ft.Delivery.cost.i4tb <- as.data.frame(f.Delivery.cost.i4tb, row.names=c(a,'total') )


#5. TOX cost
Tox.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  Tox.sum.i4tb[k, ]<- l.toxcost.i4tb[[k]]  }

Tox.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
Tox.sum.dis.i4tb[, i] <- Tox.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Tox.cost.i4tb<- rowSums(Tox.sum.dis.i4tb)
sum(Tox.cost.i4tb)

ct.Tox.cost.i4tb <- as.matrix(Tox.cost.i4tb)
sum.Tox.cost.i4tb <- as.matrix(sum(Tox.cost.i4tb))

f.Tox.cost.i4tb <- rbind(ct.Tox.cost.i4tb , sum.Tox.cost.i4tb)
colnames(f.Tox.cost.i4tb) <-c("Tox cost")

ft.Tox.cost.i4tb<- as.data.frame(f.Tox.cost.i4tb, row.names=c(a,'total') )

 
#4-1. Top-down cost
Topdowncost <- matrix( , nrow=1, ncol=2)
Topdowncost[1,1] <-31860000 #59M * 90% (HIV) * 60% (1st year)
Topdowncost[1,2] <-21240000 #59M * 90% * 40% (2nd year)
 
Topdowncost.dis <- matrix( , nrow=1, ncol=2)
for (i in 1:2) {
  Topdowncost.dis[1,i] <- Topdowncost[1,i]*(1/(1+r))^(i-1)}

Topdown.cost.i4tb<- rowSums(Topdowncost.dis)
Topdown.cost.i4tb



##.TBcost saved
TBcostsaved.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  TBcostsaved.sum.i4tb[k, ]<- colSums(l.TBcostsaved.dis.i4tb[[k]])  }

TBcostsaved.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
TBcostsaved.sum.dis.i4tb[, i] <- TBcostsaved.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

TBcost.saved.i4tb<- rowSums(TBcostsaved.sum.dis.i4tb)
sum(TBcost.saved.i4tb)

ct.TBcost.saved.i4tb <- as.matrix(TBcost.saved.i4tb)
sum.TBcost.saved.i4tb <- as.matrix(sum(TBcost.saved.i4tb))

f.TBcost.saved.i4tb <- rbind(ct.TBcost.saved.i4tb, sum.TBcost.saved.i4tb )
colnames(f.TBcost.saved.i4tb) <-c("TBCosts saved")

ft.TBcost.saved.i4tb <- as.data.frame(f.TBcost.saved.i4tb, row.names=c(a,'total') )

##.ART cost
ARTcost.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  ARTcost.sum.i4tb[k, ]<- colSums(l.ARTcost.dis.i4tb[[k]])  }

ARTcost.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
ARTcost.sum.dis.i4tb[, i] <- ARTcost.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

ARTcost.saved.i4tb<- rowSums(ARTcost.sum.dis.i4tb)
sum(ARTcost.saved.i4tb)

ct.ARTcost.saved.i4tb <- as.matrix(ARTcost.saved.i4tb)
sum.ARTcost.saved.i4tb <- as.matrix(sum(ARTcost.saved.i4tb))

f.ARTcost.saved.i4tb <- rbind(ct.ARTcost.saved.i4tb , sum.ARTcost.saved.i4tb )
colnames(f.ARTcost.saved.i4tb) <-c("ART Costs added")

ft.ARTcost.saved.i4tb <- as.data.frame(f.ARTcost.saved.i4tb, row.names=c(a,'total') )
```

```{r I4TB summary tables}

incrm.cost.I4TB <- Topdown.cost.i4tb + ft.Tox.cost.i4tb+ ft.ARTcost.saved.i4tb - ft.TBcost.saved.i4tb
colnames(incrm.cost.I4TB) <-c("incremental cost")

table.I4TB <- cbind(Topdown.cost.i4tb,ft.TBcost.saved.i4tb, ft.ARTcost.saved.i4tb, ft.Tox.cost.i4tb, incrm.cost.I4TB, ft.Case.averted.i4tb, ft.Death.averted.i4tb, ft.DALY.averted.i4tb)

write.table(table.I4TB, "table.I4TB.txt", sep="\t") 


```

```{r step3h I4TB summary_ICER}

#Total cost saved (Top-down cost)
Cost.I4TB = Topdown.cost.i4tb + sum(Tox.cost.i4tb)+ sum(ARTcost.saved.i4tb)  -sum(TBcost.saved.i4tb) 
Cost.I4TB


#ICER
ICER.I4TB= Cost.I4TB/sum(DALY.averted.i4tb)
ICER.I4TB

# 1580.22
```
# Step 3-1: I4TB direct effect (PSA)  

``` {r SA.I4tb}
treatment.sim<-function(
  LTBI=0.23,
  TBrr=0.016,
  eff=0.9,
  comp=0.8,
  fatal=0.11,
  UwHIV=0.947,
  LE=27,
  UwTB=0.601,
 tox1=0.082,
  tox2=0.003, 
 r=	0.03,
cART=	64,
price3=10,
cOPD.g1= 2.38625, 
cOPD.g2= 2.6525,
cOPD.g3= 2.38625, 
cOPD.g4=2.6525,
cinp.g1= 12.83735,
cinp.g2=12.8475,
cinp.g3=12.83735,
cinp.g4=12.8475,
clab.g1=16.31104, 
clab.g2=18.13098,
clab.g3=16.31104, 
clab.g4=18.13098,
cTB.g1= 445.839, 
cTB.g2=1039.740,  
cTB.g3=445.839, 
cTB.g4=1039.740) {

cOPD <- c(cOPD.g1, cOPD.g2, cOPD.g3, cOPD.g4)

clab <- c(clab.g1,clab.g2,clab.g3,clab.g4)

cinp <- c(cinp.g1,cinp.g2, cinp.g3, cinp.g4) 

cTB <- c(cTB.g1,cTB.g2,cTB.g3,cTB.g4) 

tox1cost <- clab*df2009 + cOPD*df 
tox2cost <- clab*df2009 + cinp*df*7

#1. I4TB cohort 

l.cohort.i4tb <- vector("list", 4)
for (k in 1:4) {
  l.cohort.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,2] 2021 cohorts
for (i in 1:2) {
  l.cohort.i4tb[[k]][1,i] <- t(m.i4tb)[k,i] 
    for (j in 2:imp.time) {
      l.cohort.i4tb[[k]][j,i] <- l.cohort.i4tb[[k]][j-1,i] - l.cohort.i4tb[[k]][j-1,i]*log(0.5)/-LE 
        }}
}

names(l.cohort.i4tb) <- paste0(a)  


#2. case

l.case.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=group name
  l.case.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.case.i4tb[[k]][i,j] <- l.cohort.i4tb[[k]][i,j]*LTBI*(1-exp(-TBrr))*eff*comp 
}}
}
names(l.case.i4tb) <- paste0(a)
  
## discounted case averted

l.case.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.case.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,2] 2021 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.case.dis.i4tb[[k]][i,j] <- l.case.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.case.dis.i4tb) <- paste0(a)

#2. death

l.death.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.death.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.death.i4tb[[k]][i,j] <- l.case.i4tb[[k]][i,j]*fatal
}}
}
names(l.death.i4tb) <- paste0(a)

## discounted death averted

l.death.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.death.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.death.dis.i4tb[[k]][i,j] <- l.death.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
} 
names(l.death.dis.i4tb) <- paste0(a)

l.DALY.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.DALY.i4tb[[k]][i,j] <- l.death.i4tb[[k]][i,j]*UwHIV*((1/r)*(1-exp(-r*(LE-i+1)))) + l.case.i4tb[[k]][i,j]*(UwHIV-UwTB)
}}
}
names(l.DALY.i4tb) <- paste0(a)

## discounted DALY averted

l.DALY.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.DALY.dis.i4tb[[k]][i,j] <- l.DALY.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
} 
names(l.DALY.dis.i4tb) <- paste0(a)



l.delivery.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.delivery.i4tb[[k]]<-matrix(NA, nrow=1, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2023 cohorts
  for (j in 1:2) {
  l.delivery.i4tb[[k]][1,j] <- l.cohort.i4tb[[k]][1,j]*(price1+3*cOPD[k]*df)*1.25
  }
}
names(l.delivery.i4tb) <- paste0(a)

#Toxicity

l.toxcost.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.toxcost.i4tb[[k]]<-matrix(NA, nrow=1, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
  for (j in 1:2) {
  l.toxcost.i4tb[[k]][1,j] <- l.cohort.i4tb[[k]][1,j]*tox1*tox1cost[k] +  l.cohort.i4tb[[k]][1,j]*tox2*tox2cost[k]
  }
}
names(l.toxcost.i4tb) <- paste0(a)

#cost saved projection

l.TBcostsaved.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.TBcostsaved.i4tb[[k]][i,j] <- l.case.i4tb[[k]][i,j]*cTB[k]
  }}
}
names(l.TBcostsaved.i4tb) <- paste0(a) 

l.ARTcost.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.ARTcost.i4tb[[k]][i,j] <- l.death.i4tb[[k]][i,j]*cART * (1/r)*(1-(1/((1+r)^(11-i))))*(1+r) 
  }}
}
names(l.ARTcost.i4tb) <- paste0(a)



## discounted cost saved

l.TBcostsaved.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.TBcostsaved.dis.i4tb[[k]][i,j] <- l.TBcostsaved.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.TBcostsaved.dis.i4tb) <- paste0(a)

l.ARTcost.dis.i4tb <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.dis.i4tb[[k]]<-matrix(NA, nrow=imp.time, ncol=2)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:2) {
  l.ARTcost.dis.i4tb[[k]][i,j] <- l.ARTcost.i4tb[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
} 
names(l.ARTcost.dis.i4tb) <- paste0(a)

#1. case averted
case.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  case.sum.i4tb[k, ]<- colSums(l.case.dis.i4tb[[k]])  }

case.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
case.sum.dis.i4tb[, i] <- case.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Case.averted.i4tb<- rowSums(case.sum.dis.i4tb)

sum.Case.averted.i4tb <- as.matrix(sum(Case.averted.i4tb))

#2. death averted
death.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  death.sum.i4tb[k, ]<- colSums(l.death.dis.i4tb[[k]])  }

death.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
death.sum.dis.i4tb[, i] <- death.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Death.averted.i4tb<- rowSums(death.sum.dis.i4tb)

sum.Death.averted.i4tb <- as.matrix(sum(Death.averted.i4tb))

 #3. DALY averted
DALY.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  DALY.sum.i4tb[k, ]<- colSums(l.DALY.dis.i4tb[[k]])  }

DALY.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
DALY.sum.dis.i4tb[, i] <- DALY.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

DALY.averted.i4tb<- rowSums(DALY.sum.dis.i4tb)

sum.DALY.averted.i4tb <- as.matrix(sum(DALY.averted.i4tb))


#4. Delivery cost
Delivery.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  Delivery.sum.i4tb[k, ]<- l.delivery.i4tb[[k]]  }

Delivery.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
Delivery.sum.dis.i4tb[, i] <- Delivery.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Delivery.cost.i4tb<- rowSums(Delivery.sum.dis.i4tb)

sum.Delivery.cost.i4tb <- as.matrix(sum(Delivery.cost.i4tb))

#5. TOX cost
Tox.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  Tox.sum.i4tb[k, ]<- l.toxcost.i4tb[[k]]  }

Tox.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
Tox.sum.dis.i4tb[, i] <- Tox.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

Tox.cost.i4tb<- rowSums(Tox.sum.dis.i4tb)

sum.Tox.cost.i4tb <- as.matrix(sum(Tox.cost.i4tb))

#5.TBcost saved
TBcostsaved.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  TBcostsaved.sum.i4tb[k, ]<- colSums(l.TBcostsaved.dis.i4tb[[k]])  }

TBcostsaved.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
TBcostsaved.sum.dis.i4tb[, i] <- TBcostsaved.sum.i4tb[, i]*(1/(1+r)^(i-1))} 


TBcost.saved.i4tb<- rowSums(TBcostsaved.sum.dis.i4tb)
 
sum.TBcost.saved.i4tb <- as.matrix(sum(TBcost.saved.i4tb))

##.ART cost
ARTcost.sum.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (k in 1:4) {
  ARTcost.sum.i4tb[k, ]<- colSums(l.ARTcost.dis.i4tb[[k]])  }

ARTcost.sum.dis.i4tb <- matrix(NA, nrow=4, ncol=2)   
for (i in 1:2) {
ARTcost.sum.dis.i4tb[, i] <- ARTcost.sum.i4tb[, i]*(1/(1+r)^(i-1))} 

ARTcost.saved.i4tb<- rowSums(ARTcost.sum.dis.i4tb)

sum.ARTcost.saved.i4tb <- as.matrix(sum(ARTcost.saved.i4tb))

#topdown cost
Topdowncost <- matrix( , nrow=1, ncol=2)
Topdowncost[1,1] <-31860000 #59M * 90% (HIV) * 60% (1st year)
Topdowncost[1,2] <-21240000 #59M * 90% * 40% (2nd year)
 
Topdowncost.dis <- matrix( , nrow=1, ncol=2)
for (i in 1:2) {
  Topdowncost.dis[1,i] <- Topdowncost[1,i]*(1/(1+r))^(i-1)}

Topdown.cost.i4tb<- rowSums(Topdowncost.dis)

sum.Topdown.cost.i4tb <- as.matrix(sum(Topdown.cost.i4tb))

#Total cost saved (drug price $15)
Cost.i4tb = sum(Delivery.cost.i4tb) + sum(Tox.cost.i4tb) + sum(ARTcost.saved.i4tb)- sum(TBcost.saved.i4tb)


#Total cost saved (Top-down cost)
Cost.topdown.i4tb = Topdown.cost.i4tb + sum(Tox.cost.i4tb) + sum(ARTcost.saved.i4tb)- sum(TBcost.saved.i4tb) 


#ICER
ICER.i4tb= Cost.i4tb/sum(DALY.averted.i4tb)

ICER.topdown.i4tb= Cost.topdown.i4tb/sum(DALY.averted.i4tb)
 
results<-c(sum.Delivery.cost.i4tb, sum.Topdown.cost.i4tb, sum.TBcost.saved.i4tb, sum.ARTcost.saved.i4tb, sum.Tox.cost.i4tb, sum.Case.averted.i4tb, sum.Death.averted.i4tb, sum.DALY.averted.i4tb, Cost.i4tb, Cost.topdown.i4tb , ICER.i4tb, ICER.topdown.i4tb)
  return(results)
  
  } 


#Define the sampling distributions for each input variable
#Alternatively, this can be imported using the function:
param.ranges<-read.csv('parameter_new_f.csv',header=T,fileEncoding="UTF-8-BOM")

param2.ranges<-data.frame("variable"=character(16),"base"=numeric(16),
                     "distribution"=character(16),
                    "parameter1"=numeric(16),
                 "parameter2"=numeric(16))

param2.ranges[,"variable"]<-c("cOPD.g1","cOPD.g2","cOPD.g3","cOPD.g4", "cinp.g1", "cinp.g2", "cinp.g3", "cinp.g4","clab.g1","clab.g2","clab.g3","clab.g4","cTB.g1","cTB.g2","cTB.g3","cTB.g4")
param2.ranges[,"distribution"]<-rep("uniform",16)
param2.ranges[,"base"]<-c(cOPD, cinp, clab, cTB)
param2.ranges[,"parameter1"]<-c(cOPD*0.5, cinp*0.5, clab*0.5, cTB*0.5)
param2.ranges[,"parameter2"]<-c(cOPD*1.5, cinp*1.5, clab*1.5, cTB*1.5)

param.ranges <- rbind(param.ranges, param2.ranges)
 
#Define the number of simulations you intend to perform

n.sims<-10000


#Create a matrix to hold all of the sampled parameter values
#Each row will represent 1 simulation; the columns in the row will correspond to the sampled parameter values for the row
sampled.values<-matrix(nrow=n.sims,ncol=nrow(param.ranges))
colnames(sampled.values)<-param.ranges[,"variable"]


#Loop over the parameters (columns in sampled.values, rows in param.ranges) that will be sampled
for(p in 1:ncol(sampled.values)){
  
  #check for the distribution that will be used
  if(param.ranges[p,"distribution"]=="uniform"){
   
     n.params<-runif( #sample from a uniform distribution
                    n.sims, #how many samples to draw = the number of simulations you will perform
                    min=param.ranges[p,"parameter1"], #define the lower bound parameter
                    max=param.ranges[p,"parameter2"] #define the upper bound
                    )
      #exit the if-loop and go to the end
     
  }
  
  
  #if not uniform, check if it is lognormal
  if(param.ranges[p,"distribution"]=="lognormal"){
    
    n.params<-rlnorm( #sample from a log-normal distribution
                    n.sims, #how many samples to draw = the number of simulations you will perform
                    meanlog=param.ranges[p,"parameter1"], #define the mean parameter
                    sdlog=param.ranges[p,"parameter2"] #define the standard deviation parameter
                  )
    #exit the if-loop and go to the end
    
  }
  
  #if not lognormal, check if is gamma
  if(param.ranges[p,"distribution"]=="gamma"){
    n.params<-rgamma( #sample from a log-normal distribution
                    n.sims, #how many samples to draw = the number of simulations you will perform
                    shape=param.ranges[p,"parameter1"], #define the k parameter
                    scale=param.ranges[p,"parameter2"] #define the theta parameter
                  )
    #exit the if-loop and go to the end
    
  }
  
  sampled.values[,p]<-n.params #fill the column of the matrix with the vector of sampled values
  
  #go to the next column
}

sim.out<-t(apply(X=sampled.values,MARGIN=1, FUN=function(r) do.call(what=treatment.sim, args=as.list(r)) ))
colnames(sim.out) <-c("Bup.cost.i4tb","Topdown.cost.i4tb","TBcost.saved.i4tb","ARTcost.saved.i4tb", "Tox.cost.i4tb", "Case.averted.i4tb", "Death.averted.i4tb", "DALY.averted.i4tb","Incre.cost.Bup.i4tb","Incre.cost.Topdown.i4tb", "ICER.Bup.i4tb", "ICER.topdown.i4tb")
#Becase treatment.sim() returns a vector of 4 results ("Scenario1.Cure","Scenario1.Cost","Scenario2.Cure","Scenario2.Cost")
  #sim.out contains 4 columns, each corresponding to one of the outputs of treatment.sim()
  #The first row of sim.out corresponds to the results of the simulation created by the first row of sampled input values in sampled.value


#Perform the ICER calculations
ICER<-matrix(ncol=5,nrow=nrow(sim.out))
colnames(ICER)<-c("Incremental.Cost","Incremental.Effectiveness", "Ratio", "Incremental.Cost.Million", "Incremental.Effectiveness.Thousand")

ICER[,"Incremental.Cost"]<-sim.out[,"Topdown.cost.i4tb"]+sim.out[,"Tox.cost.i4tb"]+sim.out[,"ARTcost.saved.i4tb"]-sim.out[,"TBcost.saved.i4tb"]
ICER[,"Incremental.Effectiveness"]<-sim.out[,"DALY.averted.i4tb"]
ICER[,"Ratio"]<-ICER[,"Incremental.Cost"]/ICER[,"Incremental.Effectiveness"]


ICER[,"Incremental.Cost.Million"]<-ICER[,"Incremental.Cost"]/1000000
ICER[,"Incremental.Effectiveness.Thousand"]<-ICER[,"Incremental.Effectiveness"]/1000

```

# Step 4: I4TB catalytic effect  
``` {r step4a S1 cohort survival projection}

#1. Catalytic cohort.

l.cohort.S1 <- vector("list", 4)
for (k in 1:4) {
  l.cohort.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:27-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:time) {
  l.cohort.S1[[k]][1,i] <- t(m.S1)[k,i] 
    for (j in 2:imp.time) {
      l.cohort.S1[[k]][j,i] <- l.cohort.S1[[k]][j-1,i] - l.cohort.S1[[k]][j-1,i]*log(0.5)/-LE 
        }}
}

## cut off effects beyond 2031  [5,10]~

for (k in 1:4){
 for (i in 1:imp.time){
  for (j in 1:time){
   if ((i+j)>12){l.cohort.S1[[k]][i,j] = 0} 
}}}

```

```{r step4b S1 case averted projection}
#2. case 

l.case.S1 <- vector("list", 4)
for (k in 1:4) { ##k=group name
  l.case.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.case.S1[[k]][i,j] <- l.cohort.S1[[k]][i,j]*LTBI*(1-exp(-TBrr))*eff*comp 
}}
}
names(l.case.S1) <- paste0(a)

## discounted case averted

l.case.S1.dis <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.case.S1.dis[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.case.S1.dis[[k]][i,j] <- l.case.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.case.S1.dis) <- paste0(a)

    
```

```{r step4c S1 death averted projection}

l.death.S1 <- vector("list", 4)
for (k in 1:4) { ##k=gr name
  l.death.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.death.S1[[k]][i,j] <- l.case.S1[[k]][i,j]*fatal
}}
}
names(l.death.S1) <- paste0(a)

## discounted death averted

l.death.S1.dis <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.death.S1.dis[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.death.S1.dis[[k]][i,j] <- l.death.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.death.S1.dis) <- paste0(a)
```

```{r step4d S1 DALY averted projection}

l.DALY.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.DALY.S1[[k]][i,j] <- l.death.S1[[k]][i,j]*UwHIV*((1/r)*(1-exp(-r*(LE-i+1)))) + l.case.S1[[k]][i,j]*(UwHIV-UwTB)
}}
}
names(l.DALY.S1) <- paste0(a)

## discounted DALY averted

l.DALY.S1.dis <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.S1.dis[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.DALY.S1.dis[[k]][i,j] <- l.DALY.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.DALY.S1.dis) <- paste0(a)
```

```{r step4e S1 delivery cost projection}

#1. base case ($15/$12/ $10)

l.delivery1.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.delivery1.S1[[k]]<-matrix(NA, nrow=1, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
  for (j in 1:2) #2020-2021 
    {  l.delivery1.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price1+3*cOPD[k]*df)*1.25
  for (j in 3:4) #2022-2023 
    {  l.delivery1.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price2+3*cOPD[k]*df)*1.25
  for (j in 5:time) #2024-
    {  l.delivery1.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price3+3*cOPD[k]*df)*1.25
  }}}
}
names(l.delivery1.S1) <- paste0(a)


#2. sensitivity analysis  ($15/$12/ $7)

l.delivery2.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.delivery2.S1[[k]]<-matrix(NA, nrow=1, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
  for (j in 1:2) #2020-2021 
    {  l.delivery2.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price1+3*cOPD[k]*df)*1.25
  for (j in 3:4) #2022-2023 
    {  l.delivery2.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price2+3*cOPD[k]*df)*1.25
  for (j in 5:time) #2024-
    {  l.delivery2.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price4+3*cOPD[k]*df)*1.25
  }}}
}
names(l.delivery2.S1) <- paste0(a)

#Toxicity


l.toxcost.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.toxcost.S1[[k]]<-matrix(NA, nrow=1, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
  for (j in 1:time) {
  l.toxcost.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*tox1*tox1cost[k] +  l.cohort.S1[[k]][1,j]*tox2*tox2cost[k]
  }
}
names(l.toxcost.S1) <- paste0(a)
```

```{r step4f S1 cost saved projection}

l.TBcostsaved.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.TBcostsaved.S1[[k]][i,j] <- l.case.S1[[k]][i,j]*cTB[k]
  }}
}
names(l.TBcostsaved.S1) <- paste0(a)   

l.ARTcost.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for(j in 1:time) {
  l.ARTcost.S1[[k]][i,j] <- l.death.S1[[k]][i,j]*cART * (1/r)*(1-(1/((1+r)^(11-i))))*(1+r) 
  }}
}
names(l.ARTcost.S1) <- paste0(a)

## discounted cost saved 

l.TBcostsaved.dis.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.dis.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.TBcostsaved.dis.S1[[k]][i,j] <- l.TBcostsaved.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.TBcostsaved.dis.S1) <- paste0(a)

l.ARTcost.dis.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.dis.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.ARTcost.dis.S1[[k]][i,j] <- l.ARTcost.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.ARTcost.dis.S1) <- paste0(a)
```

``` {r step4g S1 cost effectiveness}
#1. case averted
case.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  case.sum.S1[k, ]<- colSums(l.case.S1.dis[[k]])  }

case.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
case.sum.S1.dis[, i] <- case.sum.S1[, i]*(1/(1+r)^(i-1))} 

Case.averted.S1<- rowSums(case.sum.S1.dis)

ct.Case.averted.S1 <- as.matrix(Case.averted.S1)
sum.Case.averted.S1 <- as.matrix(sum(Case.averted.S1))

f.Case.averted.S1 <- rbind(ct.Case.averted.S1 , sum.Case.averted.S1 )
colnames(f.Case.averted.S1) <-c("cases averted")
rownames(f.Case.averted.S1) <-c(a,'total')

ft.Case.averted.S1 <- as.data.frame(f.Case.averted.S1)

#2. death averted
death.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  death.sum.S1[k, ]<- colSums(l.death.S1.dis[[k]])  }

death.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
death.sum.S1.dis[, i] <- death.sum.S1[, i]*(1/(1+r)^(i-1))} 

Death.averted.S1<- rowSums(death.sum.S1.dis)

ct.Death.averted.S1 <- as.matrix(Death.averted.S1)
sum.Death.averted.S1 <- as.matrix(sum(Death.averted.S1))

f.Death.averted.S1 <- rbind(ct.Death.averted.S1 , sum.Death.averted.S1 )
colnames(f.Death.averted.S1) <-c("Deaths averted")
rownames(f.Death.averted.S1) <-c(a,'total')

ft.Death.averted.S1 <- as.data.frame(f.Death.averted.S1)

#3. DALY averted
DALY.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  DALY.sum.S1[k, ]<- colSums(l.DALY.S1.dis[[k]])  }

DALY.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
DALY.sum.S1.dis[, i] <- DALY.sum.S1[, i]*(1/(1+r)^(i-1))} 

DALY.averted.S1<- rowSums(DALY.sum.S1.dis)

ct.DALY.averted.S1 <- as.matrix(DALY.averted.S1)
sum.DALY.averted.S1 <- as.matrix(sum(DALY.averted.S1))

f.DALY.averted.S1 <- rbind(ct.DALY.averted.S1 , sum.DALY.averted.S1 )
colnames(f.DALY.averted.S1) <-c("DALYs averted")
rownames(f.DALY.averted.S1) <-c(a,'total')

ft.DALY.averted.S1 <- as.data.frame(f.DALY.averted.S1)

#4-1. Delivery1 cost
Delivery1.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  Delivery1.sum.S1[k, ]<- l.delivery1.S1[[k]]  }

Delivery1.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
Delivery1.sum.S1.dis[, i] <- Delivery1.sum.S1[, i]*(1/(1+r)^(i-1))} 

Delivery1.cost.S1<- rowSums(Delivery1.sum.S1.dis)

ct.Delivery1.cost.S1 <- as.matrix(Delivery1.cost.S1)
sum.Delivery1.cost.S1 <- as.matrix(sum(Delivery1.cost.S1))

f.Delivery1.cost.S1 <- rbind(ct.Delivery1.cost.S1 , sum.Delivery1.cost.S1 )
colnames(f.Delivery1.cost.S1) <-c("Delivery1 cost")

ft.Delivery1.cost.S1 <- as.data.frame(f.Delivery1.cost.S1, row.names=c(a,'total') )

#4-2. Delivery2 cost
Delivery2.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  Delivery2.sum.S1[k, ]<- l.delivery2.S1[[k]]  }

Delivery2.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
Delivery2.sum.S1.dis[, i] <- Delivery2.sum.S1[, i]*(1/(1+r)^(i-1))} 

Delivery2.cost.S1<- rowSums(Delivery2.sum.S1.dis)

ct.Delivery2.cost.S1 <- as.matrix(Delivery2.cost.S1)
sum.Delivery2.cost.S1 <- as.matrix(sum(Delivery2.cost.S1))

f.Delivery2.cost.S1 <- rbind(ct.Delivery2.cost.S1 , sum.Delivery2.cost.S1 )
colnames(f.Delivery2.cost.S1) <-c("Delivery2 cost")

ft.Delivery2.cost.S1 <- as.data.frame(f.Delivery2.cost.S1, row.names=c(a,'total') )

#4455. Toxicity cost
Tox.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  Tox.sum.S1[k, ]<- l.toxcost.S1[[k]]  }

Tox.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
Tox.sum.S1.dis[, i] <- Tox.sum.S1[, i]*(1/(1+r)^(i-1))} 

Tox.cost.S1<- rowSums(Tox.sum.S1.dis)

ct.Tox.cost.S1 <- as.matrix(Tox.cost.S1)
sum.Tox.cost.S1 <- as.matrix(sum(Tox.cost.S1))

f.Tox.cost.S1 <- rbind(ct.Tox.cost.S1 , sum.Tox.cost.S1 )
colnames(f.Tox.cost.S1) <-c("Tox cost")

ft.Tox.cost.S1 <- as.data.frame(f.Tox.cost.S1, row.names=c(a,'total') )

#5.TBcost saved
TBcostsaved.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  TBcostsaved.sum.S1[k, ]<- colSums(l.TBcostsaved.dis.S1[[k]])  }

TBcostsaved.sum.dis.S1 <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
TBcostsaved.sum.dis.S1[, i] <- TBcostsaved.sum.S1[, i]*(1/(1+r)^(i-1))} 

TBcost.saved.S1<- rowSums(TBcostsaved.sum.dis.S1)

ct.TBcost.saved.S1 <- as.matrix(TBcost.saved.S1)
sum.TBcost.saved.S1 <- as.matrix(sum(TBcost.saved.S1))

f.TBcost.saved.S1 <- rbind(ct.TBcost.saved.S1 , sum.TBcost.saved.S1 )
colnames(f.TBcost.saved.S1) <-c("TBCosts saved")

ft.TBcost.saved.S1 <- as.data.frame(f.TBcost.saved.S1, row.names=c(a,'total') )


##.ART cost
ARTcost.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  ARTcost.sum.S1[k, ]<- colSums(l.ARTcost.dis.S1[[k]])  }

ARTcost.sum.dis.S1 <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
ARTcost.sum.dis.S1[, i] <- ARTcost.sum.S1[, i]*(1/(1+r)^(i-1))} 

ARTcost.saved.S1<- rowSums(ARTcost.sum.dis.S1)

ct.ARTcost.saved.S1 <- as.matrix(ARTcost.saved.S1)
sum.ARTcost.saved.S1 <- as.matrix(sum(ARTcost.saved.S1))

f.ARTcost.saved.S1 <- rbind(ct.ARTcost.saved.S1 , sum.ARTcost.saved.S1 )
colnames(f.ARTcost.saved.S1) <-c("ART Costs added")

ft.ARTcost.saved.S1 <- as.data.frame(f.ARTcost.saved.S1, row.names=c(a,'total') )
```

```{r S1 summary tables}

incrm.cost.S1 <- ft.Delivery1.cost.S1 + ft.Tox.cost.S1+ ft.ARTcost.saved.S1 - ft.TBcost.saved.S1
colnames(incrm.cost.S1) <-c("incremental cost")

incrm.cost2.S1 <- ft.Delivery2.cost.S1 + ft.Tox.cost.S1+ ft.ARTcost.saved.S1 - ft.TBcost.saved.S1
colnames(incrm.cost2.S1) <-c("incremental cost")

table.S1 <- cbind(ft.Delivery1.cost.S1,ft.TBcost.saved.S1, ft.ARTcost.saved.S1, ft.Tox.cost.S1, incrm.cost.S1, ft.Case.averted.S1, ft.Death.averted.S1, ft.DALY.averted.S1)

write.table(table.S1, "table.S1.txt", sep="\t") 

table2.S1 <- cbind(ft.Delivery2.cost.S1,ft.TBcost.saved.S1, ft.ARTcost.saved.S1, ft.Tox.cost.S1, incrm.cost2.S1, ft.Case.averted.S1, ft.Death.averted.S1, ft.DALY.averted.S1)

write.table(table2.S1, "table2.S1.txt", sep="\t") 
```

```{r step4h S1 summary_ICER}

#Total cost saved
Cost.S1 = sum(Delivery1.cost.S1)+ sum(Tox.cost.S1)+ sum(ARTcost.saved.S1)  -sum(TBcost.saved.S1) 
Cost.S1

Cost2.S1 = sum(Delivery2.cost.S1)+ sum(Tox.cost.S1) + sum(ARTcost.saved.S1)  -sum(TBcost.saved.S1) 
Cost2.S1


#ICER
ICER.S1= Cost.S1/sum(DALY.averted.S1)
ICER.S1

ICER2.S1= Cost2.S1/sum(DALY.averted.S1)
ICER2.S1


#Total cost saved including I4TB
Cost.total.S1 = Cost.S1 + Cost.I4TB
Cost2.total.S1 = Cost2.S1 + Cost.I4TB

DALY.total.S1 = sum(DALY.averted.i4tb) + sum(DALY.averted.S1)



ICER.total.S1= Cost.total.S1/DALY.total.S1
ICER.total.S1

ICER2.total.S1= Cost2.total.S1/DALY.total.S1
ICER2.total.S1

incrm.cost.I4TBS1 <- ft.Delivery1.cost.S1 + ft.Tox.cost.S1+ ft.ARTcost.saved.S1 - ft.TBcost.saved.S1 +  Topdown.cost.i4tb + sum(Tox.cost.i4tb)+ sum(ARTcost.saved.i4tb) - sum(TBcost.saved.i4tb)
colnames(incrm.cost.I4TBS1) <-c("incremental cost")

incrm.cost2.I4TBS1 <- ft.Delivery2.cost.S1 + ft.Tox.cost.S1+ ft.ARTcost.saved.S1 - ft.TBcost.saved.S1 +  Topdown.cost.i4tb + sum(Tox.cost.i4tb)+ sum(ARTcost.saved.i4tb) - sum(TBcost.saved.i4tb)
colnames(incrm.cost2.I4TBS1) <-c("incremental cost")

table.S1.plus <- cbind( ft.Delivery1.cost.S1+Topdown.cost.i4tb,ft.TBcost.saved.S1+sum(TBcost.saved.i4tb), ft.ARTcost.saved.S1+sum(ARTcost.saved.i4tb),ft.Tox.cost.S1+sum(Tox.cost.i4tb), incrm.cost.I4TBS1,  ft.Case.averted.S1+sum(Case.averted.i4tb), ft.Death.averted.S1+sum(Death.averted.i4tb), ft.DALY.averted.S1+sum(DALY.averted.i4tb))

table.S2.plus <- cbind( ft.Delivery2.cost.S1+Topdown.cost.i4tb,ft.TBcost.saved.S1+sum(TBcost.saved.i4tb), ft.ARTcost.saved.S1+sum(ARTcost.saved.i4tb),ft.Tox.cost.S1+sum(Tox.cost.i4tb), incrm.cost2.I4TBS1,  ft.Case.averted.S1+sum(Case.averted.i4tb), ft.Death.averted.S1+sum(Death.averted.i4tb), ft.DALY.averted.S1+sum(DALY.averted.i4tb))


write.table(table.S1.plus, "table.S1.plus.txt", sep="\t") 

write.table(table.S2.plus, "table.S2.plus.txt", sep="\t") 

```

# Step 4-1: I4TB catalytic effect (PSA)  
``` {r SA}
treatment2.sim<-function(
  LTBI=0.23,
  TBrr=0.016,
  eff=0.9,
  comp=0.8,
  fatal=0.11,
  UwHIV=0.947,
  LE=27,
  UwTB=0.601,
 tox1=0.082,
  tox2=0.003, 
 r=	0.03,
cART=	64,
price3=10,
cOPD.g1= 2.38625, 
cOPD.g2= 2.6525,
cOPD.g3= 2.38625, 
cOPD.g4=2.6525,
cinp.g1= 12.83735,
cinp.g2=12.8475,
cinp.g3=12.83735,
cinp.g4=12.8475,
clab.g1=16.31104, 
clab.g2=18.13098,
clab.g3=16.31104, 
clab.g4=18.13098,
cTB.g1= 445.839, 
cTB.g2=1039.740,  
cTB.g3=445.839, 
cTB.g4=1039.740) {

cOPD <- c(cOPD.g1, cOPD.g2, cOPD.g3, cOPD.g4)

clab <- c(clab.g1,clab.g2,clab.g3,clab.g4)

cinp <- c(cinp.g1,cinp.g2, cinp.g3, cinp.g4) 

cTB <- c(cTB.g1,cTB.g2,cTB.g3,cTB.g4) 

tox1cost <- clab*df2009 + cOPD*df 
tox2cost <- clab*df2009 + cinp*df*7

#1. Catalytic cohort.

l.cohort.S1 <- vector("list", 4)
for (k in 1:4) {
  l.cohort.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:27-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:time) {
  l.cohort.S1[[k]][1,i] <- t(m.S1)[k,i] 
    for (j in 2:imp.time) {
      l.cohort.S1[[k]][j,i] <- l.cohort.S1[[k]][j-1,i] - l.cohort.S1[[k]][j-1,i]*log(0.5)/-LE 
        }}
}

names(l.cohort.S1) <- paste0(a)

for (k in 1:4){
 for (i in 1:imp.time){
  for (j in 1:time){
   if ((i+j)>12){l.cohort.S1[[k]][i,j] = 0} 
  }}}

#2. case 

l.case.S1 <- vector("list", 4)
for (k in 1:4) { ##k=group name
  l.case.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.case.S1[[k]][i,j] <- l.cohort.S1[[k]][i,j]*LTBI*(1-exp(-TBrr))*eff*comp 
}}
}
names(l.case.S1) <- paste0(a)

## discounted case averted

l.case.S1.dis <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.case.S1.dis[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.case.S1.dis[[k]][i,j] <- l.case.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.case.S1.dis) <- paste0(a)

l.death.S1 <- vector("list", 4)
for (k in 1:4) { ##k=gr name
  l.death.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.death.S1[[k]][i,j] <- l.case.S1[[k]][i,j]*fatal
}}
}
names(l.death.S1) <- paste0(a)

## discounted death averted

l.death.S1.dis <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.death.S1.dis[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.death.S1.dis[[k]][i,j] <- l.death.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.death.S1.dis) <- paste0(a)

l.DALY.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.DALY.S1[[k]][i,j] <- l.death.S1[[k]][i,j]*UwHIV*((1/r)*(1-exp(-r*(LE-i+1)))) + l.case.S1[[k]][i,j]*(UwHIV-UwTB)
}}
}
names(l.DALY.S1) <- paste0(a)

## discounted DALY averted

l.DALY.S1.dis <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.DALY.S1.dis[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.DALY.S1.dis[[k]][i,j] <- l.DALY.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.DALY.S1.dis) <- paste0(a)

l.delivery1.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.delivery1.S1[[k]]<-matrix(NA, nrow=1, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,11] 2030 cohorts
  for (j in 1:2) #2020-2021 
    {  l.delivery1.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price1+3*cOPD[k]*df)*1.25
  for (j in 3:4) #2022-2023 
    {  l.delivery1.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price2+3*cOPD[k]*df)*1.25
  for (j in 5:time) #2024-
    {  l.delivery1.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*(price3+3*cOPD[k]*df)*1.25
  }}}
}
names(l.delivery1.S1) <- paste0(a)


l.toxcost.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.toxcost.S1[[k]]<-matrix(NA, nrow=1, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
  for (j in 1:time) {
  l.toxcost.S1[[k]][1,j] <- l.cohort.S1[[k]][1,j]*tox1*tox1cost[k] +  l.cohort.S1[[k]][1,j]*tox2*tox2cost[k]
  }
}
names(l.toxcost.S1) <- paste0(a)


l.TBcostsaved.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.TBcostsaved.S1[[k]][i,j] <- l.case.S1[[k]][i,j]*cTB[k]
  }}
}
names(l.TBcostsaved.S1) <- paste0(a)   

l.ARTcost.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for(j in 1:time) {
  l.ARTcost.S1[[k]][i,j] <- l.death.S1[[k]][i,j]*cART * (1/r)*(1-(1/((1+r)^(11-i))))*(1+r) 
  }}
}
names(l.ARTcost.S1) <- paste0(a)

## discounted cost saved 

l.TBcostsaved.dis.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.TBcostsaved.dis.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.TBcostsaved.dis.S1[[k]][i,j] <- l.TBcostsaved.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.TBcostsaved.dis.S1) <- paste0(a)

l.ARTcost.dis.S1 <- vector("list", 4)
for (k in 1:4) { ##k=country name
  l.ARTcost.dis.S1[[k]]<-matrix(NA, nrow=imp.time, ncol=time)   
#nrow:10-time horizon survival per cohort  
#ncol:[,1] 2020 ~ [,4] 2023 cohorts
for (i in 1:imp.time) {
  for (j in 1:time) {
  l.ARTcost.dis.S1[[k]][i,j] <- l.ARTcost.S1[[k]][i,j]*(1/(1+r)^(i-1)) 
}}
}
names(l.ARTcost.dis.S1) <- paste0(a)


#1. case averted
case.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  case.sum.S1[k, ]<- colSums(l.case.S1.dis[[k]])  }

case.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
case.sum.S1.dis[, i] <- case.sum.S1[, i]*(1/(1+r)^(i-1))} 

Case.averted.S1<- rowSums(case.sum.S1.dis)

sum.Case.averted.S1 <- as.matrix(sum(Case.averted.S1))

#2. death averted
death.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  death.sum.S1[k, ]<- colSums(l.death.S1.dis[[k]])  }

death.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
death.sum.S1.dis[, i] <- death.sum.S1[, i]*(1/(1+r)^(i-1))} 

Death.averted.S1<- rowSums(death.sum.S1.dis)

sum.Death.averted.S1 <- as.matrix(sum(Death.averted.S1))

#3. DALY averted
DALY.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  DALY.sum.S1[k, ]<- colSums(l.DALY.S1.dis[[k]])  }

DALY.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
DALY.sum.S1.dis[, i] <- DALY.sum.S1[, i]*(1/(1+r)^(i-1))} 

DALY.averted.S1<- rowSums(DALY.sum.S1.dis)

sum.DALY.averted.S1 <- as.matrix(sum(DALY.averted.S1))

#4-1. Delivery1 cost
Delivery1.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  Delivery1.sum.S1[k, ]<- l.delivery1.S1[[k]]  }

Delivery1.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
Delivery1.sum.S1.dis[, i] <- Delivery1.sum.S1[, i]*(1/(1+r)^(i-1))} 

Delivery1.cost.S1<- rowSums(Delivery1.sum.S1.dis)

sum.Delivery1.cost.S1 <- as.matrix(sum(Delivery1.cost.S1))

#4455. Toxicity cost
Tox.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  Tox.sum.S1[k, ]<- l.toxcost.S1[[k]]  }

Tox.sum.S1.dis <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
Tox.sum.S1.dis[, i] <- Tox.sum.S1[, i]*(1/(1+r)^(i-1))} 

Tox.cost.S1<- rowSums(Tox.sum.S1.dis)

sum.Tox.cost.S1 <- as.matrix(sum(Tox.cost.S1))


#5.TBcost saved
TBcostsaved.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  TBcostsaved.sum.S1[k, ]<- colSums(l.TBcostsaved.dis.S1[[k]])  }

TBcostsaved.sum.dis.S1 <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
TBcostsaved.sum.dis.S1[, i] <- TBcostsaved.sum.S1[, i]*(1/(1+r)^(i-1))} 

TBcost.saved.S1<- rowSums(TBcostsaved.sum.dis.S1)

sum.TBcost.saved.S1 <- as.matrix(sum(TBcost.saved.S1))


##.ART cost
ARTcost.sum.S1 <- matrix(NA, nrow=4, ncol=time)   
for (k in 1:4) {
  ARTcost.sum.S1[k, ]<- colSums(l.ARTcost.dis.S1[[k]])  }

ARTcost.sum.dis.S1 <- matrix(NA, nrow=4, ncol=time)   
for (i in 1:time) {
ARTcost.sum.dis.S1[, i] <- ARTcost.sum.S1[, i]*(1/(1+r)^(i-1))} 

ARTcost.saved.S1<- rowSums(ARTcost.sum.dis.S1)

sum.ARTcost.saved.S1 <- as.matrix(sum(ARTcost.saved.S1))

#Total cost saved (drug price $15)
Cost.S1 = sum(Delivery1.cost.S1)+ sum(Tox.cost.S1)+ sum(ARTcost.saved.S1)  -sum(TBcost.saved.S1) 
ICER.S1= Cost.S1/sum(DALY.averted.S1)
 
results<-c(sum.Delivery1.cost.S1, sum.TBcost.saved.S1, sum.ARTcost.saved.S1, sum.Tox.cost.S1, sum.Case.averted.S1, sum.Death.averted.S1, sum.DALY.averted.S1, Cost.S1, ICER.S1)
  return(results)
  
} 

#Define the number of simulations you intend to perform

n.sims<-10000

#Create a matrix to hold all of the sampled parameter values
#Each row will represent 1 simulation; the columns in the row will correspond to the sampled parameter values for the row
                                                                             sampled2.values<-matrix(nrow=n.sims,ncol=nrow(param.ranges))
colnames(sampled2.values)<-param.ranges[,"variable"]


#Loop over the parameters (columns in sampled.values, rows in param.ranges) that will be sampled
for(p in 1:ncol(sampled2.values)){
  
  #check for the distribution that will be used
  if(param.ranges[p,"distribution"]=="uniform"){
   
     n.params2<-runif( #sample from a uniform distribution
                    n.sims, #how many samples to draw = the number of simulations you will perform
                    min=param.ranges[p,"parameter1"], #define the lower bound parameter
                    max=param.ranges[p,"parameter2"] #define the upper bound
                    )
      #exit the if-loop and go to the end
     
  }
  
  
  #if not uniform, check if it is lognormal
  if(param.ranges[p,"distribution"]=="lognormal"){
    
    n.params2<-rlnorm( #sample from a log-normal distribution
                    n.sims, #how many samples to draw = the number of simulations you will perform
                    meanlog=param.ranges[p,"parameter1"], #define the mean parameter
                    sdlog=param.ranges[p,"parameter2"] #define the standard deviation parameter
                  )
    #exit the if-loop and go to the end
    
  }
  
  #if not lognormal, check if is gamma
  if(param.ranges[p,"distribution"]=="gamma"){
    n.params2<-rgamma( #sample from a log-normal distribution
                    n.sims, #how many samples to draw = the number of simulations you will perform
                    shape=param.ranges[p,"parameter1"], #define the k parameter
                    scale=param.ranges[p,"parameter2"] #define the theta parameter
                  )
    #exit the if-loop and go to the end
    
  }
  
  sampled2.values[,p]<-n.params2 #fill the column of the matrix with the vector of sampled values
  
  #go to the next column
}

sim.S1.out<-t(apply(X=sampled2.values,MARGIN=1, FUN=function(r) do.call(what=treatment2.sim, args=as.list(r)) ))
colnames(sim.S1.out) <-c("Delivery.cost.S1","TBcost.saved.S1","ARTcost.saved.S1", "Tox.cost.S1", "Case.averted.S1", "Death.averted.S1", "DALY.averted.S1","Incre.cost.S1","ICER.S1")
  
 #The first row of sim.out corresponds to the results of the simulation created by the first row of sampled input values in sampled.value

write.csv(sim.S1.out, "S1.sim.csv") 

#Perform the ICER calculations
ICER.S1<-matrix(ncol=3,nrow=nrow(sim.S1.out))
colnames(ICER.S1)<-c("Incremental.Cost","Incremental.Effectiveness", "Ratio")

ICER.S1[,"Incremental.Cost"]<-sim.S1.out[,"Delivery.cost.S1"]+sim.S1.out[,"Tox.cost.S1"]+sim.S1.out[,"ARTcost.saved.S1"]-sim.S1.out[,"TBcost.saved.S1"]
ICER.S1[,"Incremental.Effectiveness"]<-sim.S1.out[,"DALY.averted.S1"]
ICER.S1[,"Ratio"]<-ICER.S1[,"Incremental.Cost"]/ICER.S1[,"Incremental.Effectiveness"]

write.csv(ICER.S1, "icer.S1.sim.csv")


mean(ICER.S1[,"Incremental.Cost"])
quantile(ICER.S1[,"Incremental.Cost"], c(.025, .975)) 

mean(ICER.S1[,"Incremental.Effectiveness"])
quantile(ICER.S1[,"Incremental.Effectiveness"], c(.025, .975)) 

mean(ICER.S1[,"Ratio"])
quantile(ICER.S1[,"Ratio"], c(.025, .975)) 
```

# Step 4-2: I4TB direct effect + catalytic effect (PSA)  

```{r SA_I4TB+catalytic}

n.sim <- 10000

delivery.cost <- rep(0,n.sim)
for(k in 1:n.sim){
  delivery.cost[k] <- sample(sim.out[,"Topdown.cost.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"Delivery.cost.S1"],1,replace=TRUE)
} 

TBcost.saved <- rep(0,n.sim)
for(k in 1:n.sim){
  TBcost.saved[k] <- sample(sim.out[,"TBcost.saved.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"TBcost.saved.S1"],1,replace=TRUE)
} 

ARTcost.saved <- rep(0,n.sim)
for(k in 1:n.sim){
  ARTcost.saved[k] <- sample(sim.out[,"ARTcost.saved.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"ARTcost.saved.S1"],1,replace=TRUE)
} 

Tox.cost <- rep(0,n.sim)
for(k in 1:n.sim){
  Tox.cost[k] <- sample(sim.out[,"Tox.cost.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"Tox.cost.S1"],1,replace=TRUE)
}

Case.averted<- rep(0,n.sim)
for(k in 1:n.sim){
  Case.averted[k] <- sample(sim.out[,"Case.averted.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"Case.averted.S1"],1,replace=TRUE)
}

Death.averted<- rep(0,n.sim)
for(k in 1:n.sim){
  Death.averted[k] <- sample(sim.out[,"Death.averted.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"Death.averted.S1"],1,replace=TRUE)
}

DALY.averted<- rep(0,n.sim)
for(k in 1:n.sim){
  DALY.averted[k] <- sample(sim.out[,"DALY.averted.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"DALY.averted.S1"],1,replace=TRUE)
}

Incr.cost<- rep(0,n.sim)
for(k in 1:n.sim){
 Incr.cost[k] <- sample(sim.out[,"Incre.cost.Topdown.i4tb"],1,replace=TRUE)+
                  sample(sim.S1.out[,"Incre.cost.S1"],1,replace=TRUE)
}



ICER.final.SA<-matrix(ncol=5,nrow=n.sim)
colnames(ICER.final.SA)<-c("Incremental.Cost","Incremental.Effectiveness", "Ratio", "Incremental.Cost.Million", "Incremental.Effectiveness.Thousand")

ICER.final.SA[,"Incremental.Cost"]<-Incr.cost
ICER.final.SA[,"Incremental.Effectiveness"]<-DALY.averted
ICER.final.SA[,"Ratio"]<-ICER.final.SA[,"Incremental.Cost"]/ICER.final.SA[,"Incremental.Effectiveness"]



I4TBS1.sim <- cbind(delivery.cost,TBcost.saved,ARTcost.saved,Tox.cost ,Incr.cost, Case.averted, Death.averted,DALY.averted,ICER.final.SA[,"Ratio"]  )
  
write.csv(I4TBS1.sim , "I4TBS1.sim .csv")  



mean(ICER.final.SA[,"Incremental.Cost"])
quantile(ICER.final.SA[,"Incremental.Cost"], c(.025, .975)) 

mean(ICER.final.SA[,"Incremental.Effectiveness"])
quantile(ICER.final.SA[,"Incremental.Effectiveness"], c(.025, .975)) 

mean(ICER.final.SA[,"Ratio"])
quantile(ICER.final.SA[,"Ratio"], c(.025, .975)) 


quantile(Case.averted, c(.025, .975)) 
quantile(Death.averted, c(.025, .975)) 
quantile(DALY.averted, c(.025, .975)) 



ICER.final.SA[,"Incremental.Cost.Million"]<-ICER.final.SA[,"Incremental.Cost"]/1000000
ICER.final.SA[,"Incremental.Effectiveness.Thousand"]<-ICER.final.SA[,"Incremental.Effectiveness"]/1000


write.csv(ICER.final.SA, "icer.final.sim.csv")

```


 
